SK-1731: Updated shared build yml file

diff --git a/.github/workflows/shared-build-and-deploy.yml b/.github/workflows/shared-build-and-deploy.yml
--- a/.github/workflows/shared-build-and-deploy.yml
+++ b/.github/workflows/shared-build-and-deploy.yml
@@ -72,10 +72,31 @@ jobs:
           twine upload dist/*
 
       - name: Build and Publish to JFrog Artifactory
-        if: ${{ inputs.is-internal }}
-        env:
-          TWINE_USERNAME: ${{ secrets.JFROG_USERNAME }}
-          TWINE_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
-        run: |
-          python setup.py sdist bdist_wheel
-          twine upload --repository-url https://prekarilabs.jfrog.io/artifactory/api/pypi/skyflow-python/ dist/*
+          if: ${{ inputs.is-internal }}
+          env:
+            TWINE_USERNAME: ${{ secrets.JFROG_USERNAME }}
+            TWINE_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
+          run: |
+            # Check if TWINE_USERNAME and TWINE_PASSWORD are empty
+            if [ -z "$TWINE_USERNAME" ]; then
+              echo "TWINE_USERNAME is empty"
+            else
+              echo "TWINE_USERNAME is set"
+            fi
+
+            if [ -z "$TWINE_PASSWORD" ]; then
+              echo "TWINE_PASSWORD is empty"
+            else
+              echo "TWINE_PASSWORD is set"
+            fi
+
+            # Proceed with the build and publish if credentials are set
+            if [ -n "$TWINE_USERNAME" ] && [ -n "$TWINE_PASSWORD" ]; then
+              python setup.py sdist bdist_wheel
+              twine upload --repository-url https://prekarilabs.jfrog.io/artifactory/api/pypi/skyflow-python/ dist/*
+            else
+              echo "Error: Missing JFrog credentials. Exiting."
+              exit 1
+            fi
+
+          
